Repository laminas/laminas-coding-standard, pull requests merged in 2020-05, with the labels that each got.

#26 Adds missing project name to mkdocs configuration
  README.md
  docs/book/v1/index.md
  docs/book/v2/index.md
  mkdocs.yml
Labels: Bug

#29 QA fixes for documentation
  docs/book/v1/intro.md
  docs/book/v2/intro.md
Labels: Bug, Documentation, Enhancement

#31 Adds option for Composer installation command for dev
  mkdocs.yml
Labels: Documentation, Enhancement
