Repository laminas/laminas-coding-standard, pull requests merged in 2024-10, with the labels that each got.

#83 feat: upgrade to `slevomat/coding-standard` ^8
  composer.json
  composer.lock
  src/LaminasCodingStandard/ruleset.xml
Labels: Enhancement

#86 docs: Add missing docs for v3
  docs/book/v3/coding-style-guide.md
  docs/book/v3/intro.md
  mkdocs.yml
Labels: Documentation, Enhancement

#85 chore: Update links from squizlabs to PHPCSStandards
  README.md
Labels: Documentation, Enhancement

#88 Fix docs build workflow
  .github/workflows/docs-build.yml
Labels: Bug, Documentation
